// Deliberately NOT '../api/client'. That shared instance responds to any 401 by
// calling TokenStorage.clearAll(), so a single expired token turned one failed
// chat request into a full logout — every later call then went out with no
// Authorization header at all and the assistant stayed permanently unreachable.
//
// This client (despite living under worker/) is the only one in the app that
// refreshes the token on 401 and retries, and it reads the same storage keys and
// base URL, so it is correct for all four roles.
import apiClient from '../worker/api/client';

/**
 * Role-aware HSE assistant.
 *
 * There is deliberately no role parameter here. The backend derives both the
 * data snapshot and the assistant's persona from the JWT (see
 * `backend/app/controllers/ai.py:_role_bucket`), so a worker's client cannot
 * request a manager-scoped answer by asking for one.
 */

export type AiRole = 'user' | 'assistant';

export interface AiMessage {
  role: AiRole;
  content: string;
}

export interface AiReply {
  answer: string;
  /** Model that served the reply, or 'fallback' when no provider is configured. */
  model: string;
  /** Which role profile the backend applied: worker | supervisor | manager | auditor. */
  scope?: string;
}

/**
 * A single LLM round-trip regularly runs past the 15s default on the shared
 * client — the backend assembles a live DB snapshot and then waits on the model.
 * Anything under ~45s produces spurious timeouts on a slow connection.
 */
const AI_TIMEOUT_MS = 60000;

export async function sendAiMessage(
  userMessage: string,
  history: AiMessage[] = [],
): Promise<AiReply> {
  const messages: AiMessage[] = [...history, { role: 'user', content: userMessage }];

  const res = await apiClient.post(
    '/ai/chat',
    { messages },
    { timeout: AI_TIMEOUT_MS },
  );

  // `/ai/chat` returns a bare object, so the client's {success,data} unwrap
  // interceptor passes it through untouched.
  const body = res.data ?? {};
  const answer =
    typeof body.answer === 'string' && body.answer.trim().length > 0
      ? body.answer
      : 'No response generated by the AI service.';

  return { answer, model: body.model ?? 'unknown', scope: body.scope };
}

/**
 * Turn a failed chat request into something the user can act on.
 *
 * "Couldn't reach the assistant" was shown for every failure, including an
 * expired session — which sent people looking at their connection when the real
 * fix was signing in again.
 */
export function aiErrorText(err: any): string {
  if (err?.code === 'ECONNABORTED') {
    return 'That took too long to answer. Check your connection and try again.';
  }
  const status = err?.response?.status;
  if (status === 401) {
    return 'Your session has expired. Please sign out and sign in again.';
  }
  if (status && status >= 500) {
    return 'The assistant is having trouble on the server side. Please try again shortly.';
  }
  return "I couldn't reach the assistant just now. Please try again in a moment.";
}

/** Reports which provider the backend has configured — handy for a settings screen. */
export async function getAiStatus(): Promise<Record<string, unknown>> {
  const res = await apiClient.get('/ai/status');
  return res.data ?? {};
}
