import axiosInstance from '../api/axiosInstance';
import type { ChatMessage } from '../types';

type AiChatResponse = {
  answer?: string;
  content?: string;
  error?: string;
};

function extractAssistantText(payload: AiChatResponse): string {
  const value = payload.answer ?? payload.content;
  return typeof value === 'string' && value.trim().length > 0
    ? value
    : 'No response generated by AI service.';
}

export async function sendChatMessage(messages: ChatMessage[]): Promise<string> {
  const response = await axiosInstance.post<AiChatResponse>('/ai/chat', { messages });
  return extractAssistantText(response.data);
}

export async function chatWithAIAgent(
  userMessage: string,
  conversationHistory: ChatMessage[] = [],
): Promise<string> {
  const systemPrompt = [
    'You are an HSE (Health, Safety, and Environment) intelligence assistant.',
    'Provide concise, practical, and action-oriented responses.',
    'Use markdown formatting for readability (headings, bullets, short tables where useful).',
  ].join(' ');

  const messages: ChatMessage[] = [
    { role: 'system', content: systemPrompt },
    ...conversationHistory,
    { role: 'user', content: userMessage },
  ];

  return sendChatMessage(messages);
}

export async function analyzeViolations(violationData: unknown): Promise<string> {
  const prompt = `Analyze the following violation dataset and return: key trends, high-risk areas, and top recommendations.\n\nData:\n${JSON.stringify(violationData, null, 2)}`;
  return chatWithAIAgent(prompt);
}

export async function getPredictedRisks(historicalData: unknown): Promise<string> {
  const prompt = `Based on this historical data, provide a risk forecast with probability and preventive actions.\n\nData:\n${JSON.stringify(historicalData, null, 2)}`;
  return chatWithAIAgent(prompt);
}

export async function generateRecommendations(context: string): Promise<string> {
  return chatWithAIAgent(`Generate prioritized HSE recommendations from this context:\n\n${context}`);
}

export async function analyzeZoneRisks(zoneData: unknown): Promise<string> {
  const prompt = `Assess zone-level risk from the dataset and recommend controls by priority.\n\nData:\n${JSON.stringify(zoneData, null, 2)}`;
  return chatWithAIAgent(prompt);
}

export type { ChatMessage };

export default {
  sendChatMessage,
  chatWithAIAgent,
  analyzeViolations,
  getPredictedRisks,
  generateRecommendations,
  analyzeZoneRisks,
};
