module.exports = {
  __esModule: true,
  enableScreens: jest.fn(),
  enableFreeze: jest.fn(),
  Screen: 'Screen',
  ScreenContainer: 'ScreenContainer',
  ScreenStack: 'ScreenStack',
  ScreenStackHeaderConfig: 'ScreenStackHeaderConfig',
  ScreenStackHeaderRightView: 'ScreenStackHeaderRightView',
  ScreenStackHeaderLeftView: 'ScreenStackHeaderLeftView',
  ScreenStackHeaderCenterView: 'ScreenStackHeaderCenterView',
  ScreenStackHeaderTitleView: 'ScreenStackHeaderTitleView',
  NativeScreen: 'NativeScreen',
  NativeScreenContainer: 'NativeScreenContainer',
  NativeScreenStack: 'NativeScreenStack',
  NativeScreenStackHeaderConfig: 'NativeScreenStackHeaderConfig',
  NativeScreenStackHeaderRightView: 'NativeScreenStackHeaderRightView',
  NativeScreenStackHeaderLeftView: 'NativeScreenStackHeaderLeftView',
  NativeScreenStackHeaderCenterView: 'NativeScreenStackHeaderCenterView',
  NativeScreenStackHeaderTitleView: 'NativeScreenStackHeaderTitleView',
};
