-- Seed: working_stations
INSERT INTO working_stations (station_name, site_id, department, zone_classification, primary_hazard_id, staffing_requirement, equipment_list, permit_types_required, access_restrictions) VALUES
  ('Heavy Assembly Station 1', 1, 'Heavy Assembly', 'Heavy Assembly', 1, 3, 'Equipment Set 1', 'Hot Work', 'Authorized Personnel Only'),
  ('Light Assembly Station 2', 1, 'Light Assembly', 'Light Assembly', 2, 1, 'Equipment Set 2', 'Work at Height', 'None'),
  ('Welding Station 3', 1, 'Welding', 'Welding', 3, 1, 'Equipment Set 3', 'Confined Space', 'None'),
  ('Testing Station 4', 1, 'Testing', 'Testing', 4, 1, 'Equipment Set 4', 'Hot Work', 'Authorized Personnel Only'),
  ('Quality Inspection Station 5', 1, 'Quality Inspection', 'Quality Inspection', 5, 3, 'Equipment Set 5', 'Hot Work', 'None'),
  ('Finishing Station 1', 1, 'Finishing', 'Finishing', 6, 3, 'Equipment Set 6', 'Hot Work, Work at Height', 'None'),
  ('Maintenance Station 2', 1, 'Maintenance', 'Maintenance', 7, 1, 'Equipment Set 7', 'Hot Work', 'Authorized Personnel Only'),
  ('Heavy Assembly Station 3', 1, 'Heavy Assembly', 'Heavy Assembly', 8, 1, 'Equipment Set 8', 'Confined Space', 'None'),
  ('Light Assembly Station 4', 1, 'Light Assembly', 'Light Assembly', 9, 1, 'Equipment Set 9', 'Hot Work', 'None'),
  ('Welding Station 5', 1, 'Welding', 'Welding', 10, 3, 'Equipment Set 10', 'Confined Space', 'Authorized Personnel Only'),
  ('Testing Station 1', 1, 'Testing', 'Testing', 1, 3, 'Equipment Set 11', 'Hot Work, Work at Height', 'None'),
  ('Quality Inspection Station 2', 1, 'Quality Inspection', 'Quality Inspection', 2, 1, 'Equipment Set 12', 'Hot Work, Work at Height', 'None'),
  ('Finishing Station 3', 1, 'Finishing', 'Finishing', 3, 3, 'Equipment Set 13', 'Work at Height', 'Authorized Personnel Only'),
  ('Maintenance Station 4', 1, 'Maintenance', 'Maintenance', 4, 1, 'Equipment Set 14', 'Confined Space', 'None'),
  ('Heavy Assembly Station 5', 1, 'Heavy Assembly', 'Heavy Assembly', 5, 3, 'Equipment Set 15', 'Hot Work, Work at Height', 'None'),
  ('Light Assembly Station 1', 1, 'Light Assembly', 'Light Assembly', 6, 2, 'Equipment Set 16', 'Work at Height', 'Authorized Personnel Only'),
  ('Welding Station 2', 1, 'Welding', 'Welding', 7, 1, 'Equipment Set 17', 'Confined Space', 'None'),
  ('Testing Station 3', 1, 'Testing', 'Testing', 8, 2, 'Equipment Set 18', 'Hot Work', 'None'),
  ('Quality Inspection Station 4', 1, 'Quality Inspection', 'Quality Inspection', 9, 1, 'Equipment Set 19', 'Hot Work, Work at Height', 'Authorized Personnel Only'),
  ('Finishing Station 5', 1, 'Finishing', 'Finishing', 10, 1, 'Equipment Set 20', 'Work at Height', 'None'),
  ('Maintenance Station 1', 1, 'Maintenance', 'Maintenance', 1, 2, 'Equipment Set 21', 'Work at Height', 'None'),
  ('Heavy Assembly Station 2', 1, 'Heavy Assembly', 'Heavy Assembly', 2, 1, 'Equipment Set 22', 'Hot Work, Work at Height', 'Authorized Personnel Only'),
  ('Light Assembly Station 3', 1, 'Light Assembly', 'Light Assembly', 3, 3, 'Equipment Set 23', 'Hot Work', 'None'),
  ('Welding Station 4', 1, 'Welding', 'Welding', 4, 2, 'Equipment Set 24', 'Hot Work', 'None'),
  ('Testing Station 5', 1, 'Testing', 'Testing', 5, 3, 'Equipment Set 25', 'Work at Height', 'Authorized Personnel Only'),
  ('Quality Inspection Station 1', 1, 'Quality Inspection', 'Quality Inspection', 6, 3, 'Equipment Set 26', 'Work at Height', 'None'),
  ('Finishing Station 2', 1, 'Finishing', 'Finishing', 7, 3, 'Equipment Set 27', 'Confined Space', 'None'),
  ('Maintenance Station 3', 1, 'Maintenance', 'Maintenance', 8, 3, 'Equipment Set 28', 'Hot Work', 'Authorized Personnel Only'),
  ('Heavy Assembly Station 4', 1, 'Heavy Assembly', 'Heavy Assembly', 9, 1, 'Equipment Set 29', 'Confined Space', 'None'),
  ('Light Assembly Station 5', 1, 'Light Assembly', 'Light Assembly', 10, 2, 'Equipment Set 30', 'Hot Work', 'None'),
  ('Welding Station 1', 1, 'Welding', 'Welding', 1, 1, 'Equipment Set 31', 'Hot Work', 'Authorized Personnel Only'),
  ('Testing Station 2', 1, 'Testing', 'Testing', 2, 2, 'Equipment Set 32', 'Work at Height', 'None');
